
SUBJECT_ROLES = [
    "boaters", "substance", "seller", "victim", "farmer",
    "source", "buyer", "carrier", "eater", "experiencer",
    "farmer", "gatherers", "giver", "listener", "mourner", "perceiver",
    "performer", "seller", "sprouter", "individuals",
]

AGENT_ROLES = ["agent", "agents", "agenttype"]

OBJECT_ROLES = [
    "admired", "blocked", "bodypart", "boringthing", "caughtitem", "coagent",
    "coagentpart", "victim", "fluid", "item", "object", "student", "food", "recipient", "goods",
    "instrument",
]

PLURAL_NOUNS = [
    "people", "men", "women", "children", "teeth", "data", "alumni",
]

ROLE_PREPOSITION_MAP = {
    'tool': 'with',
    'source': 'from',
    'destination': 'to',
    'coagent': 'with',
    'coagentpart': 'with',
    'event': 'in',
    'place': 'at',
    'bottom': 'from',
    'top': 'to',
    'vehicle': 'using',
    'target': 'to',
    'quantity': 'of',
    'container': 'in',
    'created': 'at',
    'listener': 'to',
    'component': 'with',
    'from': 'from',
    'obstacle': 'over',
    'heatsource': 'using',
    'connector': 'with',
    'shape': 'in',
    'medium': 'on',
    'start': 'from',
    'end': 'to',
    'focus': 'on',
    'addressee': 'to',
    'surface': 'over',
    'goal': 'to',
    'recipient': 'to',
    'recipientpart': 'at',
    'contact': 'with',
    'against': 'against',
    'carrier': 'on',
    'material': 'on',
    'seller': 'to',
    'weapon': 'with',
}

VERB_FORM_MAPS = {
    'pressing': ('press', 'presses'),
    'putting': ('put', 'puts'),
    'practicing': ('practice', 'practices'),
    'loading': ('load', 'loads'),
    'sniffing': ('sniff', 'sniffs'),
    'glowing': ('glow', 'glows'),
    'carrying': ('carry', 'carries'),
    'pushing': ('push', 'pushes'),
    'measuring': ('measure', 'measures'),
    'scrubbing': ('scrub', 'scrubs'),
    'dipping': ('dip', 'dips'),
    'inserting': ('insert', 'inserts'),
    'throwing': ('throw', 'throws'),
    'licking': ('lick', 'licks'),
    'resting': ('rest', 'rests'),
    'brushing': ('brush', 'brushes'),
    'cleaning': ('clean', 'cleans'),
    'hoisting': ('hoist', 'hoists'),
    'fixing': ('fix', 'fixes'),
    'grimacing': ('grimace', 'grimaces'),
    'dragging': ('drag', 'drags'),
    'lifting': ('lift', 'lifts'),
    'gnawing': ('gnawing', 'gnawing'),
    'eating': ('eat', 'eat'),
    'destroying': ('destroy', 'destroys'),
    'admiring': ('admire', 'admires'),
    'riding': ('ride', 'rides'),
    'assembling': ('assemble', 'assembles'),
    'rinsing': ('rinse', 'rinses'),
    'overflowing': ('overflow', 'overflows'),
    'carting': ('cart', 'carts'),
    'pouring': ('pour', 'pours'),
    'applying': ('apply', 'applies'),
    'spraying': ('spray', 'sprays'),
    'ballooning': ('ballooning', 'ballooning'),
    'repairing': ('repair', 'repairs'),
    'foraging': ('forage', 'forages'),
    'tugging': ('tug', 'tugs'),
    'pulling': ('pull', 'pulls'),
    'smelling': ('smell', 'smells'),
    'unloading': ('unload', 'unloads'),
    'washing': ('wash', 'washes'),
    'nuzzling': ('nuzzle', 'nuzzles'),
    'sketching': ('sketch', 'sketches'),
    'chewing': ('chew', 'chews'),
    'crushing': ('crush', 'crushes'),
    'sitting': ('sit', 'sits'),
    'drawing': ('draw', 'draws'),
    'flinging': ('fling', 'flings'),
    'stacking': ('stack', 'stacks'),
    'clinging': ('cling', 'clings'),
    'examining': ('examine', 'examines'),
    'chasing': ('chase', 'chases'),
    'operating': ('operate', 'operates'),
    'dripping': ('drip', 'drips'),
    'shouting': ('shout', 'shouts'),
    'scooping': ('scoop', 'scoops'),
    'catching': ('catch', 'catches'),
    'crouching': ('crouch', 'crouches'),
    'lapping': ('lap', 'laps'),
    'dining': ('dine', 'dines'),
    'tilting': ('tilt', 'tilts'),
    'floating': ('float', 'floats'),
    'checking': ('check', 'checked'),
    'injecting': ('inject', 'injects'),
    'feeding': ('feed', 'feeds'),
    'pedaling': ('pedal', 'pedals'),
    'leaping': ('leap', 'leaps'),
    'patting': ('pat', 'pats'),
    'socializing': ('socialize', 'socializes'),
    'attaching': ('attach', 'attaches'),
    'mending': ('mend', 'mends'),
    'emerging': ('emerge', 'emerges'),
    'grinning': ('grin', 'grins'),
    'hugging': ('hug', 'hugs'),
    'discussing': ('discuss', 'discusses'),
    'hiking': ('hike', 'hikes'),
    'plummeting': ('plummet', 'plummets'),
    'stripping': ('strip', 'strips'),
    'stretching': ('stretch', 'stretches'),
    'giving': ('give', 'gives'),
    'grinding': ('grind', 'grinds'),
    'adjusting': ('adjust', 'adjusts'),
    'farming': ('farm', 'farms'),
    'rotting': ('rot', 'rots'),
    'racing': ('race', 'races'),
    'sleeping': ('sleep', 'sleeps'),
    'arranging': ('arrange', 'arranges'),
    'laughing': ('laugh', 'laughs'),
    'kicking': ('kick', 'kicks'),
    'jumping': ('jump', 'jumps'),
    'jogging': ('jog', 'jogs'),
    'manicuring': ('manicure', 'manicures'),
    'miming': ('mime', 'mimes'),
    'selling': ('sell', 'sells'),
    'dusting': ('dust', 'dusts'),
    'harvesting': ('harvest', 'harvests'),
    'surfing': ('surf', 'surfs'),
    'hanging': ('hang', 'hangs'),
    'dancing': ('dance', 'dances'),
    'shopping': ('shop', 'shops'),
    'placing': ('place', 'places'),
    'falling': ('fall', 'falls'),
    'shaking': ('shake', 'shakes'),
    'celebrating': ('celebrate', 'celebrates'),
    'rowing': ('row', 'rows'),
    'running': ('run', 'runs'),
    'opening': ('open', 'opens'),
    'kissing': ('kiss', 'kisses'),
    'saluting': ('salute', 'salutes'),
    'waving': ('wave', 'waves'),
    'peeing': ('pee', 'pees'),
    'competing': ('compete', 'competes'),
    'talking': ('talk', 'talks'),
}